version: "3"
services:
    tforex-alert:
        build: 
          context: .
          dockerfile: Dockerfile
        image: aran/tforex-alert
        ports:
            - "5000:5000"
        depends_on:
            - redis
        container_name: tforex-alert
    redis:
        image: "redis:latest"
        container_name: tforex-redis
        